### ISSUE TITLE
Ranges do not support versions with suffix tokens

### ISSUE THREAD

**Issue by alexander071** [vdurmont/semver4j#2]
According to the node-semver Tilde-Range specification listed [here](https://github.com/npm/node-semver#tilde-ranges-123-12-1), it should be possible to have a range such as this one:

`~1.2.3-beta.2` which would be equivalent to `>=1.2.3-beta.2 <1.3.0`.

However, when executed, the following code throws an exception while parsing the version range:

`new Semver("1.2.3", SemverType.NPM).satisfies("~1.2.3-beta.2");`

These also do not work:

`new Semver("1.2.3", SemverType.NPM).satisfies("^1.2.3-beta.2");`
`new Semver("1.2.3", SemverType.NPM).satisfies("1.0.0 - 1.2.3-beta.2");`

**Comment by vdurmont** [comment]
Should be available in maven central in a few hours! v2.0.1!
