### ISSUE TITLE
Please create a new release with recent changes

### ISSUE THREAD

**Issue by sschuberth** [vdurmont/semver4j#24]
As a [reminder](https://github.com/vdurmont/semver4j/pull/22#issuecomment-351449445), please create a new release with the recent fixes, in particular for issue #15.

**Comment by vdurmont** [comment]
I didn't forget, I just didn't have time to do that yesterday. I just sent an update for version 2.2.0 to maven. It'll be available in a few hours.

**Comment by sschuberth** [comment]
I didn't mean to be pushy 😉 Thanks a lot!
