### ISSUE TITLE
Matching a version against a composite range sometimes returns a wrong result

### ISSUE THREAD

**Issue by alexander071** [vdurmont/semver4j#3]
The following lines of code incorrectly return `false`:

`new Semver("1.2.0", SemverType.NPM).satisfies("1.2 <1.2.8 || >2.0.0");`
`new Semver("1.2.7", SemverType.NPM).satisfies("1.2 <1.2.8 || >2.0.0");`
`new Semver("2.0.1", SemverType.NPM).satisfies("1.2 <1.2.8 || >2.0.0");`

These however, correctly return `true`:

`new Semver("1.2.10", SemverType.NPM).satisfies("1.2.7 || >=1.2.9 <2.0.0");`
`new Semver("1.2.7", SemverType.NPM).satisfies("1.2.7 || >=1.2.9 <2.0.0");`
`new Semver("1.9.9", SemverType.NPM).satisfies("1.2.7 || >=1.2.9 <2.0.0");`

The reason for this inconsistency should be investigated.

**Comment by vdurmont** [comment]
I just released v2.0.2 with this fix. I pushed it to maven central, it should be available in a few hours.
Thanks for the help!

https://github.com/vdurmont/semver4j/releases/tag/v2.0.2
