### ISSUE TITLE
Add withSuffix (or addSuffix) and withBuild methods

### ISSUE THREAD

**Issue by punkstarman** [vdurmont/semver4j#30]
In some Maven projects that use Git Flow, I'd like to automate going from x.y.z-SNAPSHOT in the develop branch to x.y.z-CR1 in the release/x.y.z branch.

In order to transform the develop version into the release candidate version, the current API forces me to do this:
```java
Semver newVersion = new Semver(currentVersion.withClearedSuffixAndBuild() + "-CR1");
```

I would rather do this:
```java
Semver newVersion = currentVersion.withClearedSuffixAndBuild().withSuffix("-CR1");
```

**Comment by vdurmont** [comment]
Feel free to send a PR!

**Comment by vdurmont** [comment]
PR was merged, I'll be releasing a new version on maven central shortly.
