### ISSUE TITLE
Invalid operator priority

### ISSUE THREAD

**Issue by tdraier** [vdurmont/semver4j#9]
AND/OR requirements are inconsistently prioritised. OR must have lower priority than AND - a requirement like : 
"1.2 <1.2.8 || >2.0.0"
Is currently interpreted as (1.2 AND ( <1.2.8 OR >2.0.0 )), where it should be ((1.2 AND <1.2.8) OR >2.0.0)

**Comment by tdraier** [comment]
This is the cause of issue #3

**Comment by vdurmont** [comment]
I just released v2.0.2 with this fix. I pushed it to maven central, it should be available in a few hours.
Thanks for the help!

https://github.com/vdurmont/semver4j/releases/tag/v2.0.2
